# Dockerfile.dynamodb-local-setup
FROM node:20-alpine

# Install pnpm globally
RUN npm install -g pnpm
RUN npm install -g tsx

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY tsconfig.json ./
COPY .env.test ./
COPY dynamodb ./dynamodb

RUN pnpm i

CMD ["tsx", "dynamodb/schema.ts"]