# Dockerfile.dynamodb-local-setup
FROM node:20-alpine

# Install pnpm globally
RUN npm install -g pnpm
RUN npm install -g tsx

COPY package.json ./
COPY pnpm-lock.yaml ./

RUN pnpm i

COPY tsconfig.json ./
COPY tests/integration-tests/.env.test ./
COPY dynamodb ./dynamodb

CMD ["tsx", "dynamodb/schema.ts"]