/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users */
        get: operations["listUsers"];
        put?: never;
        /** Create a new user account */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a user by ID */
        get: operations["getUser"];
        /** Update a user */
        put: operations["updateUser"];
        post?: never;
        /** Delete a user */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all drivers */
        get: operations["listDrivers"];
        put?: never;
        /** Create a new driver account */
        post: operations["createDriver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/drivers/{driverId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a driver by ID */
        get: operations["getDriver"];
        /** Update a driver */
        put: operations["updateDriver"];
        post?: never;
        /** Delete a driver */
        delete: operations["deleteDriver"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pickups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pickup requests */
        get: operations["listPickups"];
        put?: never;
        /** Create a new pickup request */
        post: operations["createPickup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/pikcups/{pickupId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a pickup by ID */
        get: operations["getPickup"];
        /** Update a pickup */
        put: operations["updatePickup"];
        post?: never;
        /** Delete a pickup */
        delete: operations["deletePickup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NewUser: {
            name: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            phone?: string;
            address?: string;
        };
        UpdateUser: {
            name?: string;
            phone?: string;
            address?: string;
        };
        User: {
            id?: string;
            name?: string;
            email?: string;
            phone?: string;
            address?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        NewDriver: {
            name: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            phone?: string;
            address?: string;
        };
        UpdateDriver: {
            name?: string;
            phone?: string;
            address?: string;
            vehicleMake?: string;
            vehicleModel?: string;
            vehicleYear?: number;
        };
        Driver: {
            id?: string;
            name?: string;
            email?: string;
            phone?: string;
            address?: string;
            vehicleMake?: string;
            vehicleModel?: string;
            vehicleYear?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        NewPickup: {
            userId?: string;
            location: string;
            /** Format: float */
            estimatedWeight: number;
            wasteType: string;
            /** Format: date-time */
            requestedTime?: string;
        };
        UpdatePickup: {
            location?: string;
            /** Format: float */
            estimatedWeight?: number;
            wasteType?: string;
            /** Format: date-time */
            requestedTime?: string;
        };
        Pickup: {
            id?: string;
            userId?: string;
            driverId?: string;
            /** @enum {string} */
            status?: "pending" | "assigned" | "completed" | "cancelled";
            location?: string;
            /** Format: float */
            estimatedWeight?: number;
            wasteType?: string;
            /** Format: date-time */
            requestedTime?: string;
            /** Format: date-time */
            assignedTime?: string;
            /** Format: date-time */
            completedTime?: string;
        };
        Error: {
            code?: string;
            message?: string;
        };
    };
    responses: {
        /** @description Bad request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Access forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listUsers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users?: components["schemas"]["User"][];
                        total?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewUser"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUser"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listDrivers: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of drivers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users?: components["schemas"]["Driver"][];
                        total?: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createDriver: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewDriver"];
            };
        };
        responses: {
            /** @description Driver created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Driver"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Driver details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Driver"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driverId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDriver"];
            };
        };
        responses: {
            /** @description Driver updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Driver"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteDriver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driverId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Driver deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPickups: {
        parameters: {
            query?: {
                status?: "pending" | "assigned" | "completed" | "cancelled";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of pickup requests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pickups?: components["schemas"]["Pickup"][];
                        nextCursor?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createPickup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPickup"];
            };
        };
        responses: {
            /** @description Pickup request created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pickup"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getPickup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pickupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pickup details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pickup"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updatePickup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pickupId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePickup"];
            };
        };
        responses: {
            /** @description Pickup updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pickup"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePickup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pickupId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pickup deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
}
