name: Deploy to AWS API Gateway

on:
  push:
    branches:
      - main
    paths:
      - 'openapi.json'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region

      - name: Deploy to API Gateway
        run: |
          aws apigateway put-rest-api \
            --rest-api-id YOUR_API_ID \
            --mode overwrite \
            --body 'fileb://openapi.json'

          aws apigateway create-deployment \
            --rest-api-id YOUR_API_ID \
            --stage-name prod
